
springdoc.swagger-ui.path=/swagger-ui.html
# Fare Configuration
fare.max=7.00
fare.zone-one=2.50
fare.zone-outside-one=2.00
fare.two-zones-including-one=3.00
fare.two-zones-excluding-one=2.25
fare.three-zones=7.00
fare.bus=1.80
